INSERT INTO tag (id,parent,name) VALUES(1,NULL,'IT');
INSERT INTO tag (id,parent,name) VALUES(2,NULL,'Culture');
INSERT INTO tag (id,parent,name) VALUES(3,NULL,'Politics');
INSERT INTO tag (id,parent,name) VALUES(4,1,'Operating Systems');
INSERT INTO tag (id,parent,name) VALUES(5,1,'Database');
INSERT INTO tag (id,parent,name) VALUES(6,1,'Programming');
INSERT INTO tag (id,parent,name) VALUES(7,6,'Programming Languages');
INSERT INTO tag (id,parent,name) VALUES(8,6,'Dev Tools');
INSERT INTO tag (id,parent,name) VALUES(9,4,'Un*x Desktop');
INSERT INTO tag (id,parent,name) VALUES(10,4,'Windows');
INSERT INTO tag (id,parent,name) VALUES(11,54,'Weather');
INSERT INTO tag (id,parent,name) VALUES(12,1,'Emacs');
INSERT INTO tag (id,parent,name) VALUES(13,1,'FOSS');
INSERT INTO tag (id,parent,name) VALUES(14,1,'Cryptography');
INSERT INTO tag (id,parent,name) VALUES(15,NULL,'Life');
INSERT INTO tag (id,parent,name) VALUES(16,15,'Drugs');
INSERT INTO tag (id,parent,name) VALUES(17,15,'Sex');
INSERT INTO tag (id,parent,name) VALUES(18,17,'Porn');
INSERT INTO tag (id,parent,name) VALUES(19,1,'Cyber Cyber');
INSERT INTO tag (id,parent,name) VALUES(20,2,'Media');
INSERT INTO tag (id,parent,name) VALUES(21,2,'Movies');
INSERT INTO tag (id,parent,name) VALUES(22,2,'Literature');
INSERT INTO tag (id,parent,name) VALUES(23,2,'Music');
INSERT INTO tag (id,parent,name) VALUES(24,2,'Religion');
INSERT INTO tag (id,parent,name) VALUES(25,2,'Spocht');
INSERT INTO tag (id,parent,name) VALUES(26,3,'Authoritarianism');
INSERT INTO tag (id,parent,name) VALUES(27,1,'Security');
INSERT INTO tag (id,parent,name) VALUES(28,NULL,'International');
INSERT INTO tag (id,parent,name) VALUES(29,28,'Europa');
INSERT INTO tag (id,parent,name) VALUES(30,28,'Middle East');
INSERT INTO tag (id,parent,name) VALUES(31,28,'Africa');
INSERT INTO tag (id,parent,name) VALUES(32,28,'Asia');
INSERT INTO tag (id,parent,name) VALUES(33,28,'Australia');
INSERT INTO tag (id,parent,name) VALUES(34,28,'America');
INSERT INTO tag (id,parent,name) VALUES(35,29,'Germany');
INSERT INTO tag (id,parent,name) VALUES(36,35,'NRW');
INSERT INTO tag (id,parent,name) VALUES(37,36,'Bielefeld');
INSERT INTO tag (id,parent,name) VALUES(38,35,'Ossis');
INSERT INTO tag (id,parent,name) VALUES(39,29,'France');
INSERT INTO tag (id,parent,name) VALUES(40,29,'UK');
INSERT INTO tag (id,parent,name) VALUES(41,29,'Russia');
INSERT INTO tag (id,parent,name) VALUES(42,34,'USA');
INSERT INTO tag (id,parent,name) VALUES(43,34,'Latin America');
INSERT INTO tag (id,parent,name) VALUES(44,34,'Canada');
INSERT INTO tag (id,parent,name) VALUES(45,32,'China');
INSERT INTO tag (id,parent,name) VALUES(46,32,'Japan');
INSERT INTO tag (id,parent,name) VALUES(47,32,'India');
INSERT INTO tag (id,parent,name) VALUES(48,32,'Iran');
INSERT INTO tag (id,parent,name) VALUES(49,32,'Afghanistan');
INSERT INTO tag (id,parent,name) VALUES(50,1,'Hardware');
INSERT INTO tag (id,parent,name) VALUES(51,1,'Retro');
INSERT INTO tag (id,parent,name) VALUES(52,1,'Virtualization');
INSERT INTO tag (id,parent,name) VALUES(53,29,'Ukraine');
INSERT INTO tag (id,parent,name) VALUES(54,NULL,'Nature');
INSERT INTO tag (id,parent,name) VALUES(55,54,'Environment');
INSERT INTO tag (id,parent,name) VALUES(56,54,'Animals');
INSERT INTO tag (id,parent,name) VALUES(57,3,'Human Rights');
INSERT INTO tag (id,parent,name) VALUES(58,57,'Migrants');
INSERT INTO tag (id,parent,name) VALUES(59,57,'Privacy');
INSERT INTO tag (id,parent,name) VALUES(60,26,'Surveillance');
INSERT INTO tag (id,parent,name) VALUES(61,3,'Rightwing');
INSERT INTO tag (id,parent,name) VALUES(62,61,'Antisemitism');
INSERT INTO tag (id,parent,name) VALUES(63,61,'Racism');
INSERT INTO tag (id,parent,name) VALUES(64,61,'Fascism');
INSERT INTO tag (id,parent,name) VALUES(65,3,'Protest');
INSERT INTO tag (id,parent,name) VALUES(66,3,'Class Struggle');
INSERT INTO tag (id,parent,name) VALUES(67,3,'Economy');
INSERT INTO tag (id,parent,name) VALUES(68,54,'Climate');
INSERT INTO tag (id,parent,name) VALUES(69,54,'Disaster');
INSERT INTO tag (id,parent,name) VALUES(70,3,'War');
INSERT INTO tag (id,parent,name) VALUES(71,3,'Democracy');
INSERT INTO tag (id,parent,name) VALUES(72,71,'Elections');
INSERT INTO tag (id,parent,name) VALUES(73,1,'Internet');
INSERT INTO tag (id,parent,name) VALUES(74,73,'eMail');
INSERT INTO tag (id,parent,name) VALUES(75,73,'WWW');
INSERT INTO tag (id,parent,name) VALUES(76,20,'Podcasting');
INSERT INTO tag (id,parent,name) VALUES(77,1,'Games');
INSERT INTO tag (id,parent,name) VALUES(78,1,'Artificial Intelligence');
INSERT INTO tag (id,parent,name) VALUES(79,15,'Health');
INSERT INTO tag (id,parent,name) VALUES(80,79,'Covid-19');
INSERT INTO tag (id,parent,name) VALUES(81,79,'Mental Health');
INSERT INTO tag (id,parent,name) VALUES(82,NULL,'Science');
INSERT INTO tag (id,parent,name) VALUES(83,82,'Physics');
INSERT INTO tag (id,parent,name) VALUES(84,83,'Astronomy');
INSERT INTO tag (id,parent,name) VALUES(85,82,'Biology');
INSERT INTO tag (id,parent,name) VALUES(86,82,'Medicine');
INSERT INTO tag (id,parent,name) VALUES(87,15,'Space');
INSERT INTO tag (id,parent,name) VALUES(88,21,'TV');
INSERT INTO tag (id,parent,name) VALUES(89,6,'Web Dev');
INSERT INTO tag (id,parent,name) VALUES(90,82,'History');
INSERT INTO tag (id,parent,name) VALUES(91,90,'Archaeology');
INSERT INTO tag (id,parent,name) VALUES(92,15,'ACAB');
INSERT INTO tag (id,parent,name) VALUES(93,15,'RIP');
INSERT INTO tag (id,parent,name) VALUES(94,15,'Law');
INSERT INTO tag (id,parent,name) VALUES(95,94,'Criminal');
INSERT INTO tag (id,parent,name) VALUES(96,32,'Korea');
INSERT INTO tag (id,parent,name) VALUES(97,15,'Disaster');
INSERT INTO tag (id,parent,name) VALUES(98,15,'Fail');
INSERT INTO tag (id,parent,name) VALUES(99,3,'Propaganda');
INSERT INTO tag (id,parent,name) VALUES(100,3,'Infrastructure');
INSERT INTO tag (id,parent,name) VALUES(101,100,'Energy');
INSERT INTO tag (id,parent,name) VALUES(102,15,'LGBTQ+');
INSERT INTO tag (id,parent,name) VALUES(103,3,'Qrazy');
INSERT INTO tag (id,parent,name) VALUES(104,3,'Riots');
INSERT INTO tag (id,parent,name) VALUES(105,3,'Education');
INSERT INTO tag (id,parent,name) VALUES(106,2,'Art');
INSERT INTO tag (id,parent,name) VALUES(107,29,'Turkey');
INSERT INTO tag (id,parent,name) VALUES(108,82,'Math');
INSERT INTO tag (id,parent,name) VALUES(109,119,'Debian');
INSERT INTO tag (id,parent,name) VALUES(110,4,'BSD');
INSERT INTO tag (id,parent,name) VALUES(111,15,'Weirdos');
INSERT INTO tag (id,parent,name) VALUES(112,3,'Corruption');
INSERT INTO tag (id,parent,name) VALUES(113,NULL,'WTF');
INSERT INTO tag (id,parent,name) VALUES(114,3,'Anarchism');
INSERT INTO tag (id,parent,name) VALUES(115,15,'Fools');
INSERT INTO tag (id,parent,name) VALUES(116,73,'Social Media');
INSERT INTO tag (id,parent,name) VALUES(117,67,'Embargo');
INSERT INTO tag (id,parent,name) VALUES(118,15,'Education');
INSERT INTO tag (id,parent,name) VALUES(119,4,'Linux');
INSERT INTO tag (id,parent,name) VALUES(120,119,'Red Hat');
INSERT INTO tag (id,parent,name) VALUES(121,15,'Ethics');
INSERT INTO tag (id,parent,name) VALUES(122,52,'Cloud');
INSERT INTO tag (id,parent,name) VALUES(123,119,'SuSE');
INSERT INTO tag (id,parent,name) VALUES(124,4,'Shell');
INSERT INTO tag (id,parent,name) VALUES(125,15,'Captain Obvious');
INSERT INTO tag (id,parent,name) VALUES(126,15,'Hypocrisy');
INSERT INTO tag (id,parent,name) VALUES(127,15,'Stupid');

